services:
    app:
        image: shinsenter/laravel:php8.2
        ports:
            - '${APP_PORT:-8000}:80'
        command: bash -c "
            apt update -y
            && apt install git -y
            && tail -f /dev/null"
        tty: true
        environment:
            DISABLE_AUTORUN_COMPOSER_INSTALL: 1
            MAINTAINER: 'opensource@nfebe.com'
            APP_USER: 'laratition'
        volumes:
            - '.:/var/www/html'
            - '~/.ssh:/root/.ssh:ro'
        networks:
            - sail
        depends_on:
            - mysql

    mysql:
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sailmysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s

    phpmyadmin:
        image: 'phpmyadmin/phpmyadmin:latest'
        ports:
            - '8080:80'
        environment:
            PMA_HOST: mysql
            PMA_USER: '${DB_USERNAME}'
            PMA_PASSWORD: '${DB_PASSWORD}'
        depends_on:
            - mysql
        networks:
            - sail

    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - sail

networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
